# The URL the site will be built for
# base_url = "https://arsmachina.net"
base_url = "https://deadcomputersociety.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Taxonomies
taxonomies = [
    {name = "tags", rss = true},
    {name = "categories", rss = true}
]

title = "The Dead Computer Society"
theme = "arsmateria-zola-theme"
[extra]
# Put all your custom variables here
subtitle = "Carpe codice; Sieze the code"
author = "Brady O'Leary"
copyright_year = 2023
default_description = "The DeadComputerSociety is a collection of projects, music, and other media that Brady has created."
keywords = []

# Menu Config
menu_data_path="data/menu.json" # Load menu data from a path
# Tag config
tag_data_path="data/tags.json" # Load menu data from a path